apiVersion: v2
name: hello-world
description: A Helm chart for Kubernetes
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: grafana
    version: 6.59.0
    repository: "file://./charts/grafana"
